spring.application.name=ProductFinal

# =========================
# DATABASE CONFIG
# =========================

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# =========================
# FLYWAY CONFIG
# =========================
spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration
server.port=8080